# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

pages_list:
  About: '/about'
  Archive: '/archive'

# Setup
title:               Hiroyuki Vincent Yamazaki
tagline:             Reserach & Dev Blog by Hiroyuki Vincent Yamazaki
url:                 http://hvy.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Hiroyuki Vincent Yamazaki
  url:               https://www.hiroyukivincentyamazaki.com
  email:             hiroyuki.vincent.yamazaki@gmail.com

# Custom vars
version:             2.0.0
github:              hvy
  repo:              https://github.com/hvy/
