# Permalinks
gems:                [jekyll-paginate]
permalink:           pretty
paginate:            5
paginate_path:       "page:num"

pages_list:
  About: '/about'
  Archive: '/archive'

# Setup
title:               greatConvensions
tagline:             A Programming/Research Blog by Hiroyuki Vincent Yamazaki
url:                 https://hvy.github.io
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Hiroyuki Vincent Yamazaki
  url:               https://www.hiroyukivincentyamazaki.com
  email:             hiroyuki.vincent.yamazaki@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/hvy
